version: '3.8'

services:
  youtube-transcription:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"  # Altere a porta conforme necessário
    environment:
      - PYTHONUNBUFFERED=1